backend:
  name: github
  repo: PaulPuscas/whereabouts-tales
  branch: main
  base_url: https://whereabouts-tales-552297569132.us-west1.run.app
  auth_endpoint: /api/auth

site_url: https://whereabouts-tales-552297569132.us-west1.run.app
display_url: https://whereabouts-tales-552297569132.us-west1.run.app

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'episodes'
    label: 'Podcast Episodes'
    folder: 'content/episodes'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'YouTube Video ID', name: 'youtubeId', widget: 'string', required: false }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
